version: "3.8"

services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ex_libris_admin
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: ex_libris_db

    ports:
      - "5432:5432"